<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Incorrect email or password. Please t_566e02</name>
   <tag></tag>
   <elementGuidId>ca3f7f51-8c60-48ad-99d0-03000e67ad8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.sign-in-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Sign in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebd36fa9-f2f9-4462-b300-e749b5b7b1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign-in-btn</value>
      <webElementGuid>a103b58b-f51c-4e5d-8f4b-031804ab786a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d017d703-0c83-4422-bb22-be9c1b15d03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>8856b0c5-3d41-4c3b-a1cc-11791ce735ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>41e191a4-7efd-426a-8d49-0ec1e842f541</value>
      <webElementGuid>704117c5-49c2-4534-b3c2-f6f8f09f3834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;SignIn_wrapSignIn__jdoQJ&quot;]/div[@class=&quot;sign_up_section&quot;]/div[@class=&quot;sign_up_form&quot;]/form[@class=&quot;form_sign_up&quot;]/input[@class=&quot;sign-in-btn&quot;]</value>
      <webElementGuid>eb3714da-916b-4024-b2f1-ef4352169c98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Sign in']</value>
      <webElementGuid>9a8ba0e1-02aa-4453-8463-502231d84408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/div/form/input</value>
      <webElementGuid>57f4ab0e-544f-4474-99fa-7f427c3fd276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>99a0a4ab-2328-4e13-98ce-40af9ba41341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>e0c06d91-a2fc-4507-be1d-92452635bb53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
