<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Valid email is required to activate p_255484</name>
   <tag></tag>
   <elementGuidId>4cf5ab4a-c859-4a46-9927-f78987c1c2dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signin_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signin_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eee53f1d-eef2-40cb-8d9d-748c2afb29f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d5c051db-08ca-46ce-a567-22ac42069018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_pass</value>
      <webElementGuid>ac3bb2b3-868b-4711-a24b-36db8768b832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin_password</value>
      <webElementGuid>5e12e8a4-908b-44b2-9598-6cde532fef1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>564cf654-c893-49d7-bfb2-61569b8d990a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>0ba7206a-ca1d-499b-adfc-8a135dacff21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>5c1989e6-1555-4961-85bb-2e618061d49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-changed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6af32cd9-2cb0-4ab4-8a44-a47343ea4b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin_password&quot;)</value>
      <webElementGuid>a18a74bc-2a1d-4538-af84-141b776f801f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signin_password']</value>
      <webElementGuid>b539c65e-2708-4683-a7e6-d67e14984dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/div/form/div[2]/input</value>
      <webElementGuid>79f8945e-5b68-43dc-a998-246e10103774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c0cbb335-ecda-487a-9802-31ff54c8459d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'user_pass' and @id = 'signin_password' and @placeholder = 'Password']</value>
      <webElementGuid>384fd8d5-60dc-4dbb-85a5-0e0acc9d3e4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
