<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>L1_Category1_HP</name>
   <tag></tag>
   <elementGuidId>25d0b878-f62e-4b2b-9231-b7b79e5acb52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='a-dekstop__categoryLink']//span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>6cc184e3-ce2e-475e-9c11-e1847b7a27ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678033965677</value>
      <webElementGuid>05575e62-105d-4948-a059-ab550563a24c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
