<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_sjagtapkognivera.com</name>
   <tag></tag>
   <elementGuidId>9e60f8fa-fb47-4e2d-a768-85520a7f78f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-muted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='user']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c60df23-c551-4f6d-8831-f9b8609265ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-muted</value>
      <webElementGuid>07b51df3-687d-43c7-bdbb-ba2fde16e34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>c0b80ad9-8fe7-42d5-b9ce-0fcd393d137a</value>
      <webElementGuid>92756200-3c69-4ee7-a0bc-04ce8d116e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sjagtap@kognivera.com</value>
      <webElementGuid>39503079-3479-4f92-98ee-4a189bb395fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user&quot;)/div[@class=&quot;user-profile&quot;]/div[@class=&quot;text-muted&quot;]</value>
      <webElementGuid>52cf7add-9102-4a52-a8d3-0c4a45d8768d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='user']/div/div[2]</value>
      <webElementGuid>ef716acc-c2cc-49fe-b6c3-7549c4032d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shubham Jagtap'])[1]/following::div[1]</value>
      <webElementGuid>3509d63e-5b75-4898-8e13-ccb7b61e5ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SJ'])[2]/following::div[1]</value>
      <webElementGuid>e1ebb1a8-0a31-4261-920b-118b3d639867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Profile'])[1]/preceding::div[1]</value>
      <webElementGuid>fea3fb61-9d70-499d-9b05-164d7883fef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification Settings'])[1]/preceding::div[2]</value>
      <webElementGuid>226576c8-c0b9-40d1-9afc-0d4f40a36df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sjagtap@kognivera.com']/parent::*</value>
      <webElementGuid>b5e83ac0-b22c-4d67-87ca-51760da4ce1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[2]</value>
      <webElementGuid>f93c2409-f56a-4d2a-9828-0fdb63e5fd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'sjagtap@kognivera.com' or . = 'sjagtap@kognivera.com')]</value>
      <webElementGuid>52609f5b-606c-4c6c-8dc6-1e849f0333bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
