<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_SJShubham Jagtapsjagtapkognivera.comView_b196ca</name>
   <tag></tag>
   <elementGuidId>b2903e87-400c-4bf8-97d4-3641b3876816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fee31be7-0b9b-456a-a3a8-b7252f71686a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiListItem-root MuiListItem-gutters MuiListItem-padding css-g8a67y</value>
      <webElementGuid>0c091a43-7c9f-49ae-a847-28c7a7e48ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user</value>
      <webElementGuid>7a023de6-2f47-416f-bede-50c2563ab473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>f1714a30-d835-485d-a3ab-c2ce8a9ae94f</value>
      <webElementGuid>a0312a79-ba60-47b7-aa83-b863f1364a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SJShubham Jagtapsjagtap@kognivera.comView Profile</value>
      <webElementGuid>86fa31d9-554a-4fdb-b6aa-79c2029faeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user&quot;)</value>
      <webElementGuid>dd4fdff1-5b02-430c-ab60-794d8c5bcc4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='user']</value>
      <webElementGuid>1f6b6fb9-c538-438c-83f1-5ca0541ec42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simple-popover']/div[3]/nav/div/ul/li</value>
      <webElementGuid>d340be66-ae81-4cb0-9d7b-1d856cf15d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'user', '&quot;', ')/div[@class=', '&quot;', 'user-profile', '&quot;', ']')])[1]/following::li[1]</value>
      <webElementGuid>d8d3c6ca-e2aa-4caf-a245-533efceeaeed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete project'])[1]/following::li[1]</value>
      <webElementGuid>eb2560c2-a726-4444-bde4-5e10619c085b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li</value>
      <webElementGuid>458ff2cd-d7b9-4f70-b849-6153be35a85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'user' and (text() = 'SJShubham Jagtapsjagtap@kognivera.comView Profile' or . = 'SJShubham Jagtapsjagtap@kognivera.comView Profile')]</value>
      <webElementGuid>df4f8587-8592-4652-aeca-91f021660a2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
