<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View all projects</name>
   <tag></tag>
   <elementGuidId>e73f3775-51be-4ad1-8b4f-08d34213d3a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.p-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a02c9f48-867c-49c8-9fb0-851513b05477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackid</name>
      <type>Main</type>
      <value>view-all-projects</value>
      <webElementGuid>1e1de131-5552-4f53-8ca8-7645d77ba163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/api/v1/katone/page/admin/organization/1091126/teams/projects</value>
      <webElementGuid>ea832727-6d94-4ff5-b50a-6be7c9f604cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0</value>
      <webElementGuid>cc15f5a7-3c49-43f6-9770-fa3f5487a545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-groupid</name>
      <type>Main</type>
      <value>access-report</value>
      <webElementGuid>d68926cd-fce4-443f-9d06-6de4519f0f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>9836048c-6705-4b2d-8736-25eceac98220</value>
      <webElementGuid>7e7c8b6f-a75e-48d1-b542-57c91b163456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View all projects</value>
      <webElementGuid>857cc023-9191-48b6-956d-41ea9ebd8c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;main-body-wrapper&quot;]/div[@class=&quot;main-body&quot;]/div[@class=&quot;d-flex align-items-start&quot;]/a[@class=&quot;p-0&quot;]</value>
      <webElementGuid>d1f512cc-9093-4e2d-8e02-eaec16b1b9bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div/a</value>
      <webElementGuid>4fe70907-3dc0-4af1-815c-a5ad9cc2aca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View all projects')]</value>
      <webElementGuid>8c467d8d-0609-4bb2-bdca-71c8522d0829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Projects'])[1]/following::a[1]</value>
      <webElementGuid>79de1660-be03-4bc1-bf5b-2bfdfee56232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to My Organization_01'])[1]/following::a[1]</value>
      <webElementGuid>e5bf0aa5-bf1f-48ae-9295-b4abfda67712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FP'])[1]/preceding::a[1]</value>
      <webElementGuid>2e5891ae-00df-42ac-87ac-73fae95d317e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View all projects']/parent::*</value>
      <webElementGuid>63d3c2ac-63be-4d68-ab6b-aa886c0ca5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/api/v1/katone/page/admin/organization/1091126/teams/projects')]</value>
      <webElementGuid>64e2139d-c625-4ed6-9f76-f9ae2f30b349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>4aead0f3-ca17-47a8-9aa6-ac4f81630447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/api/v1/katone/page/admin/organization/1091126/teams/projects' and (text() = 'View all projects' or . = 'View all projects')]</value>
      <webElementGuid>88dbc8f0-bc58-40d5-9173-ace4aa8679df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
