<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SJ</name>
   <tag></tag>
   <elementGuidId>d0b80c6b-1f45-4b0a-87c6-5f76b520991d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-right-navbar']/button[2]/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c6a48c83-7075-4ff1-8d09-931fcd0a7f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>8fb040ff-14b6-4728-8038-9c3a7a7ccd13</value>
      <webElementGuid>7182bcae-1962-4b5c-8170-7c2e97c794ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SJ</value>
      <webElementGuid>b5cd7d68-49ce-4be5-bac9-f5e884ed0b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-right-navbar&quot;)/button[@class=&quot;MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5&quot;]/div[@class=&quot;avatar&quot;]/div[@class=&quot;rounded-circle sb-avatar sb-avatar--text&quot;]/div[@class=&quot;rounded-circle sb-avatar__text&quot;]/div[1]/span[1]</value>
      <webElementGuid>175a3a5d-3a49-4c55-9b6c-581d9fe65ffb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-right-navbar']/button[2]/div/div/div/div/span</value>
      <webElementGuid>55933fa2-5157-4f73-97d8-a6c4b3ec8b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Studio'])[1]/following::span[4]</value>
      <webElementGuid>76edc832-c125-4bf2-bc70-2bc46d23a9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Organization_01'])[1]/following::span[6]</value>
      <webElementGuid>3bef7beb-392f-4406-bd7b-d8c93b63512f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to My Organization_01'])[1]/preceding::span[5]</value>
      <webElementGuid>978fb0a6-303a-46e9-85c8-df552b9366d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>97afea4a-3aa8-43c6-882e-53a4cfd44ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SJ' or . = 'SJ')]</value>
      <webElementGuid>6da1f296-0997-4211-aa96-3b302273f7d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
